import React from 'react';
import Head from 'next/head';

function Header () {
  return (
    <Head>
      <title>Tony 777</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css' />
      <link rel="stylesheet" href="css/style.css" />
    </Head>
  );
}

export default Header;
